os:
- linux
- osx
before_install:
# git config
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
# updates
- if [ `uname` != 'Darwin' ]; then sudo apt-get update -qq; fi
- if [ `uname` == 'Darwin' ]; then brew update; fi
# install tools
- if [ `uname -m` = x86_64 ] && [ `uname` != 'Darwin' ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch build-essential; fi
- if [ `uname` == 'Darwin' ]; then cd /usr/local && git checkout 716d4a9 Library/Formula/cmake.rb && brew install cmake && cd -; fi
- if [ `uname` == 'Darwin' ]; then brew install gcc --enable-cxx; fi
before_script:
- ./dependencies.sh
script:
- ./build.sh
deploy:
  - provider: releases
    api_key:
      secure: C37RSFHtkBhB1/H6dNM6z9h6MdCXZGZ6og8HfzunrIDTxYa8erLXNowGgOHBNwAl2ticn0fo7aBSa0WA65GINsFx+VTGyLYlmwFIF1Heps15f2vtdehbj+AB4RWh4bvT9xzG2aNUUsx57tHgt22TJwzH7Z1
    file: ntr-cpp-Linux.tar.gz
    on:
      repo: NicolasTr/ntr-cpp
      tags: true
      all_branches: true
      condition: $TRAVIS_OS_NAME == 'linux'
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: C37RSFHtkBhB1/H6dNM6z9h6MdCXZGZ6og8HfzunrIDTxYa8erLXNowGgOHBNwAl2ticn0fo7aBSa0WA65GINsFx+VTGyLYlmwFIF1Heps15f2vtdehbj+AB4RWh4bvT9xzG2aNUUsx57tHgt22TJwzH7Z1
    file: ntr-cpp-Darwin.tar.gz
    on:
      repo: NicolasTr/ntr-cpp
      tags: true
      all_branches: true
      condition: $TRAVIS_OS_NAME == 'osx'
    skip_cleanup: true
  

